// AUTO-GENERATED BY generate_serialization.py - DO NOT EDIT
#pragma once
#include <cstring>
#include <cstdint>
#include "state_serialization.h"

namespace FrameZero {

// Specialization for PhysicsBody3D (from physics_body_3d.h)
template<>
struct Serializer<PhysicsBody3D> {
    static constexpr size_t getSize() {
        return sizeof(uint32_t) + sizeof(bool) + sizeof(Vector3) + sizeof(Vector3) + sizeof(Vector3) + sizeof(Vector3) + sizeof(Fixed) + sizeof(Fixed) + sizeof(Quaternion) + sizeof(Vector3) + sizeof(Vector3) + sizeof(Fixed) + sizeof(Fixed) + sizeof(Fixed) + sizeof(Fixed) + sizeof(uint32_t) + sizeof(uint32_t);
    }

    static void serialize(const PhysicsBody3D& obj, uint8_t* buffer) {
        size_t offset = 0;
        std::memcpy(buffer + offset, &obj.id, sizeof(uint32_t));
        offset += sizeof(uint32_t);
        std::memcpy(buffer + offset, &obj.active, sizeof(bool));
        offset += sizeof(bool);
        std::memcpy(buffer + offset, &obj.position, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(buffer + offset, &obj.velocity, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(buffer + offset, &obj.acceleration, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(buffer + offset, &obj.size, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(buffer + offset, &obj.mass, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(buffer + offset, &obj.invMass, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(buffer + offset, &obj.orientation, sizeof(Quaternion));
        offset += sizeof(Quaternion);
        std::memcpy(buffer + offset, &obj.angularVelocity, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(buffer + offset, &obj.torque, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(buffer + offset, &obj.inertia, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(buffer + offset, &obj.invInertia, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(buffer + offset, &obj.restitution, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(buffer + offset, &obj.friction, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(buffer + offset, &obj.collisionCategory, sizeof(uint32_t));
        offset += sizeof(uint32_t);
        std::memcpy(buffer + offset, &obj.collisionMask, sizeof(uint32_t));
        offset += sizeof(uint32_t);
    }

    static void deserialize(PhysicsBody3D& obj, const uint8_t* buffer) {
        size_t offset = 0;
        std::memcpy(&obj.id, buffer + offset, sizeof(uint32_t));
        offset += sizeof(uint32_t);
        std::memcpy(&obj.active, buffer + offset, sizeof(bool));
        offset += sizeof(bool);
        std::memcpy(&obj.position, buffer + offset, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(&obj.velocity, buffer + offset, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(&obj.acceleration, buffer + offset, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(&obj.size, buffer + offset, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(&obj.mass, buffer + offset, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(&obj.invMass, buffer + offset, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(&obj.orientation, buffer + offset, sizeof(Quaternion));
        offset += sizeof(Quaternion);
        std::memcpy(&obj.angularVelocity, buffer + offset, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(&obj.torque, buffer + offset, sizeof(Vector3));
        offset += sizeof(Vector3);
        std::memcpy(&obj.inertia, buffer + offset, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(&obj.invInertia, buffer + offset, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(&obj.restitution, buffer + offset, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(&obj.friction, buffer + offset, sizeof(Fixed));
        offset += sizeof(Fixed);
        std::memcpy(&obj.collisionCategory, buffer + offset, sizeof(uint32_t));
        offset += sizeof(uint32_t);
        std::memcpy(&obj.collisionMask, buffer + offset, sizeof(uint32_t));
        offset += sizeof(uint32_t);
    }
};

} // namespace FrameZero
