import os
import re
import sys

# Regex to find structs marked with // @FrameZeroComponent
COMPONENT_REGEX = re.compile(r'//\s*@FrameZeroComponent\s+struct\s+(\w+)\s*\{([^}]+)\};', re.MULTILINE)
# Regex to find variable declarations (e.g. "int hp;", "Fixed speed;")
VAR_REGEX = re.compile(r'^\s*([A-Za-z0-9_:]+)\s+([A-Za-z0-9_]+)\s*;', re.MULTILINE)

def parse_and_generate(directory):
    print(f"Scanning directory {directory} for FrameZero components...")
    
    components = []
    
    # 1. Scan all headers
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith('.h') or file.endswith('.hpp'):
                filepath = os.path.join(root, file)
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                    for match in COMPONENT_REGEX.finditer(content):
                        struct_name = match.group(1)
                        body = match.group(2)
                        
                        variables = []
                        for v_match in VAR_REGEX.finditer(body):
                            v_type = v_match.group(1)
                            v_name = v_match.group(2)
                            variables.append((v_type, v_name))
                            
                        if variables:
                            components.append((struct_name, variables))
                            print(f"Found component: {struct_name} with {len(variables)} variables.")

    if not components:
        print("No @FrameZeroComponent structs found.")
        return

    # 2. Generate the serialization header
    out_path = os.path.join(directory, 'generated_serializers.h')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("// AUTO-GENERATED BY framezero_parser.py - DO NOT EDIT\n")
        f.write("#pragma once\n")
        f.write("#include <cstring>\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace FrameZero {\n\n")
        
        for struct_name, variables in components:
            f.write(f"template<>\n")
            f.write(f"struct Serializer<{struct_name}> {{\n")
            
            # getSize()
            f.write(f"    static constexpr size_t getSize() {{\n")
            f.write(f"        return ")
            sizes = [f"sizeof({v_type})" for v_type, v_name in variables]
            f.write(" + ".join(sizes) + ";\n")
            f.write(f"    }}\n\n")
            
            # serialize()
            f.write(f"    static void serialize(const {struct_name}& obj, uint8_t* buffer) {{\n")
            f.write(f"        size_t offset = 0;\n")
            for v_type, v_name in variables:
                f.write(f"        std::memcpy(buffer + offset, &obj.{v_name}, sizeof({v_type}));\n")
                f.write(f"        offset += sizeof({v_type});\n")
            f.write(f"    }}\n\n")
            
            # deserialize()
            f.write(f"    static void deserialize({struct_name}& obj, const uint8_t* buffer) {{\n")
            f.write(f"        size_t offset = 0;\n")
            for v_type, v_name in variables:
                f.write(f"        std::memcpy(&obj.{v_name}, buffer + offset, sizeof({v_type}));\n")
                f.write(f"        offset += sizeof({v_type});\n")
            f.write(f"    }}\n")
            f.write(f"}};\n\n")
            
        f.write("} // namespace FrameZero\n")
        
    print(f"Successfully generated {out_path}!")

if __name__ == '__main__':
    target_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
    parse_and_generate(target_dir)
